### PR TITLE
Subpath highlighting fix with empty url

### LINKED ISSUE #188: Blank url and highligh_on_subpath = true causes error.
Thanks for the neat solution :)
I have hit a small (but blocking) bug!
## Repro steps

simple-navigation v4.0.3 
mri 2.2.1p85
rails 4.2.3
- configure multiple groups of items whose parents have no URL (are just groupings)
- set `highlight_on_subpath` to true
## Observations
- setting highlight_on_subpath to false stops the error, but using `highlights_on` is much less fun!
- setting the url of the parent stops the error, but the parent items are of course links then
- setting the url of the second parent also stops the error
## Example

``` ruby
# config/tasty_nav.rb
SimpleNavigation::Configuration.run do |navigation|
  # this is important
  navigation.highlight_on_subpath = true

  navigation.items do |primary|
    primary.item :first_id, 'first' do |sub_nav| # note no url argument
      sub_nav.item :first_child_id, 'first child', 'some url'
    end

    primary.item :second_id, 'second' do |sub_nav| # no url argument here either
      sub_nav.item :second_child_id, 'first child', 'some other url'
    end
  end
end
```

And render it like this

```
<%= render_navigation context: :tasty_nav, expand_all: true %>
```

(I tried disabling expand_all as well, but no effect)
## Error

```
TypeError: no implicit conversion of nil into String
simple-navigation (4.0.3) lib/simple_navigation/item.rb:177:in `escape'
simple-navigation (4.0.3) lib/simple_navigation/item.rb:177:in `selected_by_subpath?'
simple-navigation (4.0.3) lib/simple_navigation/item.rb:163:in `autohighlight_by_subpath?'
simple-navigation (4.0.3) lib/simple_navigation/item.rb:159:in `selected_by_autohighlight?'
simple-navigation (4.0.3) lib/simple_navigation/item.rb:104:in `selected_by_condition?'
simple-navigation (4.0.3) lib/simple_navigation/item.rb:45:in `selected?'
simple-navigation (4.0.3) lib/simple_navigation/item_container.rb:109:in `any?'
simple-navigation (4.0.3) lib/simple_navigation/item_container.rb:109:in `selected?'
simple-navigation (4.0.3) lib/simple_navigation/item.rb:99:in `selected_by_subnav?'
simple-navigation (4.0.3) lib/simple_navigation/item.rb:45:in `selected?'
simple-navigation (4.0.3) lib/simple_navigation/item.rb:73:in `selected_class'
simple-navigation (4.0.3) lib/simple_navigation/item.rb:55:in `html_options'
simple-navigation (4.0.3) lib/simple_navigation/renderer/list.rb:32:in `block in list_content'
simple-navigation (4.0.3) lib/simple_navigation/renderer/list.rb:31:in `map'
simple-navigation (4.0.3) lib/simple_navigation/renderer/list.rb:31:in `list_content'
simple-navigation (4.0.3) lib/simple_navigation/renderer/list.rb:23:in `render'
simple-navigation (4.0.3) lib/simple_navigation/item_container.rb:103:in `render'
simple-navigation (4.0.3) lib/simple_navigation/helpers.rb:88:in `render_navigation'
... 
```

https://github.com/codeplant/simple-navigation/blob/master/lib/simple_navigation/item.rb#L177

### PR DESCRIPTION
**Pull request by ilyapoz**
close #188

### CODE REVIEW

**Comment by ilyapoz** [comment]
You guys have some problems with travis build, I'm quite new to ruby still, so wasn't able to quickly resolve it. I did manage to run them locally.

**Comment by andi** [comment]
Yeah travis build is an issue currently, did not have time yet to investigate...

**Comment by ilyapoz** [comment]
It breaks locally in the same way. If some time soon I will dig into testing gems I might send a pr.

**Comment by andi** [comment]
I guess I fixed the travis build. default rake task was spec:all which loops through all versions, this does not make sense for travis...

**Comment by andi** [comment]
released 4.0.5

**Pull request merged**
